FROM node:15

RUN mkdir /Users/meishavernell/Desktop/FearlessTech/DockerFile

WORKDIR  Desktop/FearlessTech

COPY package.json Desktop/FearlessTech

RUN npm install

COPY . Desktop/FearlessTech

EXPOSE 3000

CMD ["npm", "start"]